{{- if and .Values.console.enabled .Values.console.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "rustfs-operator.consoleServiceAccountName" . }}
  namespace: {{ include "rustfs-operator.namespace" . }}
  labels:
    {{- include "rustfs-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: console
  {{- with .Values.console.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
