{{- if and .Values.console.enabled .Values.console.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "rustfs-operator.fullname" . }}-console
  labels:
    {{- include "rustfs-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: console
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "rustfs-operator.fullname" . }}-console
subjects:
  - kind: ServiceAccount
    name: {{ include "rustfs-operator.consoleServiceAccountName" . }}
    namespace: {{ include "rustfs-operator.namespace" . }}
{{- end }}
